.catalog:
  name: "Spark"
  version: "v1"
  description: "Spark Cluster"
  uuid: spark
  questions:
    - variable: "scale"
      description: "Number of Spark Worker nodes."
      label: "Spark Worker Nodes:"
      required: true
      default: 1
      type: "int"
    - variable: "cores"
      description: "SPARK WORKER CORES."
      label: "SPARK WORKER CORES:"
      required: true
      default: 2
      type: "int"
    - variable: "memory"
      description: "SPARK WORKER MEMORY."
      label: "SPARK WORKER MEMORY(GB):"
      required: true
      default: 1
      type: "int"
master:
  scale: 1
worker:
  scale: ${scale}