.catalog:
  name: "MongoDB"
  version: "1.0"
  description: "Mongos"
  uuid: mongodb-1
  minimum_rancher_version: v0.46.0
  questions:
    - variable: host_label
      label: "Host Label to MongoDB Tags"
      description: |
        Host label to use as MongoDB 'value' tag.
        Example: 'database'
      required: false
      type: "string"
    - variable: debug
      description: "Enable Debug log for Mongo containers"
      label: "Debug"
      type: "string"
      required: false
      default: ""
mongo-cluster:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "rs0"
mongo-cluster2:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "rs1"
mongo-cluster3:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "rs2"
mongo-cfg:
  scale: 3
  retain_ip: true
mongos:
  scale: 3
  retain_ip: true